### ISSUE TITLE
Similar Thing

### ISSUE THREAD

**Issue by W4RH4WK** [dfkt/win10-unfuck#1]
Hiho, just wanted to let you know that I started a similar project some time ago.

Have a look and see if you can reuse something from it:

https://github.com/W4RH4WK/Debloat-Windows-10/

**Comment by simplypeachy** [comment]
There's also DisableWinTracking:

https://github.com/10se1ucgo/DisableWinTracking

**Comment by dfkt** [comment]
Thanks for the link - great resources!

**Comment by dfkt** [comment]
Added the two links to the readme, cheers.

**Comment by W4RH4WK** [comment]
:beers: thanks
