### ISSUE TITLE
UAC / run as administrator

### ISSUE THREAD

**Issue by simplypeachy** [dfkt/win10-unfuck#3]
Rather than suggest your users disable UAC you can instead direct them to run the batch files as administrator:
* Right-click batch file
* Click "Run As Administrator"
* Accept UAC prompt

Or to open a command prompt which will run all commands as administrator:
* Press Windows key
* Type in: command prompt
* Right click Command Prompt entry, click on "Run As Administrator".

Teaching users to disable UAC habitually will result in their computer's security being compromised - there are no circumstances where the average user should reduce the UAC settings, and as geeks it's our job to try to keep them practising good habits :-)

**Comment by dfkt** [comment]
I'm surely not trying to teach anybody anything - certainly not an average "end user". I hope they won't go to my Github for advice. :^)

Stuff like eg. the Flash removal script won't work with the "polite" method you mentioned. It needs the admin account taken out of approval mode to operate correctly. Unfortunately "Run as Administrator" is a far cry from actually being an admin on one's own machine.

**Comment by dfkt** [comment]
Linked your concern in the readme.

This repo surely isn't meant for teaching end users how to screw/unscrew their machines, but for people who already know what they're doing (and who are actually aware of these privacy issues). Either way, can't hurt to have the 'polite' way of using UAC mentioned :^)
