### ISSUE TITLE
Blocking IP addresses?

### ISSUE THREAD

**Issue by odan** [dfkt/win10-unfuck#4]
The hosts file contains only the mappings of IP addresses to host names and not IP addresses to IP addresses.

The following command creates an outbound rule to block all traffic from the local computer to a IP address like "2.22.61.43"

netsh advfirewall firewall add rule name="Block MS IP Address 2.22.61.43" dir=out protocol=any remoteip="2.22.61.43" profile=any action=block

Test if it's working

ping 2.22.61.43
General error.

More IP addresses:
2.22.61.43
2.22.61.66
157.56.106.189

**Comment by dfkt** [comment]
Thank you. Yeah, the hosts file doesn't block IP addresses - I didn't think that far when posting the lists.

Added a separate script for these known hosts - https://github.com/dfkt/win10-unfuck/blob/master/data-harvesting-ips-firewall-block.bat
