### ISSUE TITLE
0.0.0.0 is better; no IPv6 blocking

### ISSUE THREAD

**Issue by TazeTSchnitzel** [dfkt/win10-unfuck#5]
Null-routing hosts with `0.0.0.0` is better than `127.0.0.1` because it won't try to spam localhost with requests that way.

Also, you should also include lines with the IPv6 equivalent, `::`, just in case.

**Comment by dfkt** [comment]
Thank you. I will update accordingly.

**Comment by 10se1ucgo** [comment]
0.0.0.0 will then spam every address. 127.0.0.0 might be an even better option.

**Comment by TazeTSchnitzel** [comment]
No, it won't. `0.0.0.0` doesn't do multicast in this context.
